### ISSUE TITLE
Allow to specify headings level as range

### ISSUE THREAD

**Issue by lptn** [manogi/nova-tiptap#18]
By SEO and accessibility [and standards], it's better to have only one H1 per page. For this reason it will be nice to specify available headers as a range or a list, e.g. `[3,4,5,6]`. Is it possible right now? If now, can we have this feature in the package?

PS: thanks for your great package!

**Comment by manogi** [comment]
Ah - ok, that is an interesting point. Not possible at the moment, but should be relatively easy to integrate. I would probably make it so that the `headingLevels` method can accept either an integer (current functionality) or an array, which would be the new functionality you propose. I will keep you posted here.

**Comment by lptn** [comment]
@manogi 
that will be amazing! I'll wait for this feature 👍

**Comment by desaintflorent** [comment]
I'm interested in this functionality too !

**Comment by manogi** [comment]
This is now done in Release 0.4.0 (see Readme part about heading levels).

**Comment by desaintflorent** [comment]
That was fast 👍
