### ISSUE TITLE
List items broken on detail page

### ISSUE THREAD

**Issue by stuartcusackie** [manogi/nova-tiptap#29]
Just a small bug here. List items are being marked up to contain paragraphs on the details page:

![image](https://user-images.githubusercontent.com/20210934/94922681-90811300-04b2-11eb-9930-0884b62d3653.png)

**Comment by manogi** [comment]
Thanks for the heads-up - this is now fixed in v1.2.1 by adding styles to the detail field.
Because the actual problem ist that the underlying ProseMirror wraps the li content in p tags - and this cannot be remedied in my package and neither in the underlying tiptap package, see this issue incase you are interested:

https://github.com/ueberdosis/tiptap/issues/118
