### ISSUE TITLE
Default values does'nt work

### ISSUE THREAD

**Issue by keizah7** [manogi/nova-tiptap#43]
https://nova.laravel.com/docs/3.0/resources/fields.html#default-values

```
Tiptap::make('Rules', 'rules')
    ->hideFromIndex()
    ->rules('nullable', 'min:5', 'max:5000')
    ->buttons(TipTapTrait::buttons())
    ->headingLevels(TipTapTrait::allHeadings())
//                ->resolveUsing(fn () => 'Manogi\Tiptap')
    ->default(fn () => 'default.'),
```

**Comment by manogi** [comment]
@keizah7 hi there - please describe steps to reproduce your problem. When I test it with exactly the code from the docs it works nicely, and also your version `->default(fn () => 'default.')` works nicely for me. When I use it creating a new Resource, "default." ist the content of my editor. So I'm not sure what exactly the problem is?

**Comment by keizah7** [comment]
It works for me too now. Thanks
