### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Aliaaaam** [manogi/nova-tiptap#48]
Is there any way to add rtl support as well?

**Comment by manogi** [comment]
Hi @Aliaaaam,
would like to help here, but I need to know more exaclty what you had in mind. Would it be enough that all block elements inside the editor had the attribute `dir="auto"`, so that they automatically are RTL when using for example arabic text? Or is it needed to have an option to set the whole editor to `dir="rtl"` ?

**Comment by Aliaaaam** [comment]
Hey @manogi 
I think having a button to switch between `dir="rtl"` and `dir="ltr"` in blocks is more appropriate.

**Comment by manogi** [comment]
RTL is now supported as button that switches rtl on and off:

![CleanShot 2022-01-10 at 12 47 54@2x](https://user-images.githubusercontent.com/1419634/148761252-b2f8e3f5-d05a-43a5-847e-ca97a6d30c00.png)

<img width="999" alt="CleanShot 2022-01-10 at 12 48 30@2x" src="https://user-images.githubusercontent.com/1419634/148761317-0c495fca-f782-4226-a682-de3fcf49cfb6.png">
